version: '3.8'
services:
  backend: 
    build: .
    container_name: nestjs_api
    environment: 
      - PORT=${APP_PORT}
      - JWT_SECRET_KEY=AmORAgeCyZDUwYzU3MzEzN2Q5ZjYyMjJhMDRhOTk2ZGM
      - MONGODB_URI=mongodb://0.0.0.0:27017/amor_agency
      - JWT_EXPIRES=1d
      - MAILER_INCOMING_USER=anhhv@1bitlab.io
      - MAILER_INCOMING_PASS=ljarleybszacduuj
      - MAILER_INCOMING_PORT=587
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start
    env_file:
      - .env

volumes:
  mongodb_data_container: