version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  backend: 
    build: .
    container_name: nestjs_api
    environment: 
      - PORT=${APP_PORT}
      - JWT_SECRET_KEY=AmORAgeCyZDUwYzU3MzEzN2Q5ZjYyMjJhMDRhOTk2ZGM
      - MONGODB_URI=mongodb://127.0.0.1:27017/amor_agency
      - JWT_EXPIRES=1d
      - MAILER_INCOMING_USER=anhhv@1bitlab.io
      - MAILER_INCOMING_PASS=ljarleybszacduuj
      - MAILER_INCOMING_PORT=587
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  mongodb_data_container: